### ISSUE TITLE
FEATURE REQUEST - yaml definition of tests

### ISSUE THREAD

**Issue by PapsOu** [blast-project/TestsBundle#4]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| Version  | x.y.z

A very usefull feature for defining tests actions for selenium would be to have a yaml representation of tests : 

```php
<?php
$I = new WebGuy($scenario);
$I->wantTo("Login");
$I->amOnPage("/login");
$I->fillField("//input[@id='_username']", "myUsername");
$I->fillField("//input[@id='_password']", "myPassword");
$I->click("//button[@type='submit']");
```

Represented in yaml like that :

```yaml
scenario:
    wantTo: "Login"
    amOnPage: "/login"
    fillField: 
        selector: "//input[@id='_username']"
        value: "myUsername"
    fillField: 
        selector: "//input[@id='_password']"
        value: "myPassword"
    click: 
        selector: "//button[@type='submit']"
```
